const state={protein:null,veg:[],flavor:null,combo:null,goal:null,step:"protein"};
const $=id=>document.getElementById(id);
const proteinObj=()=>PROTEINS.find(p=>p.id===state.protein);
const flavorObj=()=>FLAVORS.find(f=>f.id===state.flavor);
const vegObjs=()=>state.veg.map(id=>VEG.find(v=>v.id===id)).filter(Boolean);
const isComplete=()=>!!(state.protein&&state.veg.length===2&&state.flavor);
function mixPieces(){const bits=[];if(state.protein)bits.push({emo:proteinObj().emo,name:proteinObj().name});vegObjs().forEach(v=>bits.push({emo:v.emo,name:v.name}));if(state.flavor)bits.push({emo:flavorObj().emo,name:flavorObj().name});return bits;}
function currentStep(){if(!state.protein)return"protein";if(state.veg.length<2)return"veg";if(!state.flavor)return"flavor";return"done";}
function renderProgress(){const step=currentStep();const items=[{id:"protein",label:"Protein"},{id:"veg",label:"Vegetables"},{id:"flavor",label:"Seasoning"}];const order={protein:0,veg:1,flavor:2,done:3};$("progress").innerHTML=items.map((item,i)=>{const done=order[step]>i,on=step===item.id;const canJump=done||item.id==="protein"||(item.id==="veg"&&state.protein)||(item.id==="flavor"&&state.veg.length===2);return `<div class="pip${on?" on":""}${done?" done":""}"><button data-jump="${item.id}" ${canJump?"":"disabled"}><span class="n">${done?"\u2713":i+1}</span> ${item.label}</button></div>`;}).join("");}
function pickedRow(){const bits=[];if(state.protein)bits.push(`<span class="chip">${proteinObj().emo} ${proteinObj().name}</span>`);vegObjs().forEach(v=>bits.push(`<span class="chip">${v.emo} ${v.name}</span>`));if(state.flavor)bits.push(`<span class="chip">${flavorObj().emo} ${flavorObj().name}</span>`);const labels=["Protein","Vegetable","Vegetable","Seasoning"];while(bits.length<4)bits.push(`<span class="chip ghost">${labels[bits.length]}</span>`);return `<div class="picked">${bits.join("")}</div>`;}
function tileHtml(list,kind,selected){return list.map(x=>`<button class="tile ${selected(x)?"on":""}" data-kind="${kind}" data-id="${x.id}" data-emo="${x.emo}"><span class="emo">${x.emo}</span><span class="nm">${x.name}</span><span class="cut">${x.cut||x.style}</span></button>`).join("");}
function renderStep(){const step=state.step==="done"?"flavor":state.step;const card=$("stepCard");if(step==="protein"){card.innerHTML=`<h2>Protein <span class="qty">Station 1 \u00b7 8 oz</span></h2><p class="hint">One protein. Dry it. That's how you get color.</p>${pickedRow()}<div class="tiles three" id="proteinTiles"></div><div class="step-actions"><button class="btn btn-soft" id="surpriseBtn">Chef's choice</button></div>`;$("proteinTiles").innerHTML=tileHtml(PROTEINS,"protein",p=>state.protein===p.id);}if(step==="veg"){card.innerHTML=`<h2>Vegetables <span class="qty">Station 2 \u00b7 1 lb</span></h2><p class="hint">Two vegetables, 8 oz each. Cut them so they cook in the same pan.</p>${pickedRow()}<div class="tiles three" id="vegTiles"></div><div class="step-actions"><button class="btn-tiny" data-jump="protein">\u2190 Change protein</button><button class="btn btn-primary ${state.veg.length===2?"":"hidden"}" id="nextFlavor">Seasoning \u2192</button></div>`;$("vegTiles").innerHTML=tileHtml(VEG,"veg",v=>state.veg.includes(v.id));}if(step==="flavor"){card.innerHTML=`<h2>Seasoning <span class="qty">Station 3 \u00b7 bloom in fat</span></h2><p class="hint">Pick a kitchen. The spices go in after the protein browns.</p>${pickedRow()}<div class="tiles flavor-tiles" id="flavorTiles"></div><div class="step-actions"><button class="btn-tiny" data-jump="veg">\u2190 Change vegetables</button></div>`;$("flavorTiles").innerHTML=tileHtml(FLAVORS,"flavor",f=>state.flavor===f.id);}}
function updatePot(){const bits=mixPieces();$("potMix").innerHTML=bits.map((b,i)=>`<span class="i${i}" title="${b.name}">${b.emo}</span>`).join("");$("plate").classList.toggle("empty",bits.length===0);$("fillDots").innerHTML=bits.map(b=>`<span class="dot" title="${b.name}">${b.emo}</span>`).join("");if(!state.protein)$("potStatus").textContent="Empty pan. Protein first.";else if(state.veg.length<2)$("potStatus").textContent="Protein's in. Two vegetables.";else if(!state.flavor)$("potStatus").textContent="Now the seasoning.";else $("potStatus").textContent="Ticket's written.";}
function renderCombos(){const wrap=$("comboWrap");if(state.step!=="protein"&&state.step!=="veg"){wrap.classList.add("hidden");return;}let list=COMBOS.slice();if(state.protein)list=list.filter(c=>c.protein===state.protein);if(!list.length){wrap.classList.add("hidden");return;}$("comboTitle").textContent=state.protein?proteinObj().name+" \u2014 house plates":"House plates";$("comboRow").innerHTML=list.slice(0,4).map(c=>{const fl=FLAVORS.find(f=>f.id===c.flavor);return `<button class="combo" data-combo="${c.id}"><div class="c-emo">${c.emo}</div><div class="c-name">${c.name}</div><div class="c-meta">${fl.name} \u00b7 ${c.hook}</div></button>`;}).join("");wrap.classList.remove("hidden");}
function applyCombo(id){const c=COMBOS.find(x=>x.id===id);if(!c)return;state.combo=id;state.protein=c.protein;state.veg=c.veg.slice(0,2);state.flavor=c.flavor;state.step="done";renderAll();showResult();}
function surprise(){let pool=COMBOS.slice();if(state.goal==="spicy")pool=pool.filter(c=>FLAVORS.find(f=>f.id===c.flavor).spicy);if(state.goal==="cheap")pool=pool.filter(c=>["eggs","turkey","chicken","beef"].includes(c.protein));if(state.goal==="fast")pool=pool.filter(c=>["eggs","shrimp","salmon"].includes(c.protein));if(state.goal==="protein")pool=pool.filter(c=>["turkey","shrimp","salmon","chicken"].includes(c.protein));if(state.goal==="delicious")pool=pool.filter(c=>c.delicious>=5);if(state.protein)pool=pool.filter(c=>c.protein===state.protein);if(!pool.length)pool=COMBOS;applyCombo(pool[Math.floor(Math.random()*pool.length)].id);}
function applyGoal(goal){state.goal=goal;document.querySelectorAll(".goal").forEach(g=>g.classList.toggle("on",g.dataset.goal===goal));$("builder").classList.add("show");$("goals").classList.add("show");if(goal==="none"||goal==="delicious"){surprise();return;}if(goal==="protein")state.protein=state.protein||"shrimp";if(goal==="veggies")state.veg=["broccoli","cabbage"];if(goal==="cheap"){state.protein=["eggs","turkey","chicken"].includes(state.protein)?state.protein:"eggs";state.veg=["cabbage","onion"];}if(goal==="fast"){state.protein=["shrimp","eggs","salmon"].includes(state.protein)?state.protein:"shrimp";state.veg=["spinach","zucchini"];}if(goal==="spicy")state.flavor=state.flavor||"cajun";state.step=currentStep()==="done"?"flavor":currentStep();renderAll();if(isComplete())showResult();}
function nutrition(){const p=proteinObj(),vs=vegObjs();return{cal:Math.round(p.cal+vs.reduce((s,v)=>s+v.cal,0)),protein:Math.round(p.protein+vs.reduce((s,v)=>s+v.protein,0)),fiber:Math.round(vs.reduce((s,v)=>s+v.fiber,0)*10)/10,cost:(p.cost+vs.reduce((s,v)=>s+v.cost,0)+0.55).toFixed(2),time:Math.max(p.time,8)+6};}
function potName(){if(state.combo){const c=COMBOS.find(x=>x.id===state.combo);if(c)return{emo:c.emo,name:c.name,hook:c.hook};}const match=COMBOS.find(c=>c.protein===state.protein&&c.flavor===state.flavor&&c.veg[0]===state.veg[0]);if(match)return{emo:match.emo,name:match.name,hook:match.hook};const near=COMBOS.find(c=>c.protein===state.protein&&c.flavor===state.flavor);if(near)return{emo:near.emo,name:flavorObj().name+" "+proteinObj().name,hook:near.hook};return{emo:flavorObj().emo,name:flavorObj().name+" "+proteinObj().name,hook:flavorObj().note};}
function methodSteps(){const p=proteinObj(),f=flavorObj(),vs=vegObjs();const firm=vs.filter(v=>v.firm).map(v=>v.name.toLowerCase());const soft=vs.filter(v=>!v.firm).map(v=>v.name.toLowerCase());const vegLine=firm.length&&soft.length?`Add the ${firm.join(" and ")} first. Give them a minute of color, then fold in the ${soft.join(" and ")}.`:`Add the ${vs.map(v=>v.name.toLowerCase()).join(" and ")}. Let them take on a little color before you stir.`;const proteinStep=p.id==="eggs"?"Cook the vegetables and spices first. The eggs go in last over medium heat until just set.":(p.id==="shrimp"||p.id==="salmon")?p.sear+" If the pan is crowded, sear in two batches and hold them on a plate.":`Heat the pan until a drop of water skitters. Add ${f.fat}. ${p.sear} Salt as soon as it hits the metal.`;const mid=p.id==="eggs"?"Push the vegetables aside and scramble the eggs into the pan. Soft curds. Pull before they look done.":(p.id==="shrimp"||p.id==="salmon")?"Return the protein. Toss once through the glaze. Ten seconds, then off the heat.":"Taste. If it is flat, it needs salt. If it is heavy, it needs the finish.";return[`Mise: 8 oz ${p.name.toLowerCase()} (${p.cut}); 8 oz each vegetable, cut as written; spices measured; ${f.finish.toLowerCase()} standing by.`,proteinStep,vegLine+" Don't flood the pan. Water is the enemy of browning.",`Drop the heat a notch. Add ${f.spices.join(", ")}. Stir 20-30 seconds until the kitchen smells finished, not raw. Loosen with ${f.liquid}.`,mid,`Finish off heat with ${f.finish.toLowerCase()}. Rest one minute. Eat from a warm plate.`];}
function showResult(){if(!isComplete()){$("result").classList.remove("show");return;}const p=proteinObj(),f=flavorObj(),vs=vegObjs(),n=nutrition(),title=potName();$("recipeCard").innerHTML=`<div class="badge">Line ticket</div><h2>${title.emo} ${title.name}</h2><p class="lede">${title.hook}</p><div class="ticket"><span>12-inch skillet</span><span>Medium-high, then down</span><span>~${n.time} min</span><span>${f.spicy?"Heat: yes":"Heat: quiet"}</span></div><div class="dish-plate"><div class="plate"><div class="plate-food">${mixPieces().map((b,i)=>`<span class="i${i}">${b.emo}</span>`).join("")}</div></div></div><div class="section-label">Mise en place</div><div class="ing-list"><div class="ing"><b>${p.emo}</b> <span>8 oz ${p.name} \u00b7 ${p.cut}</span><span class="amt">1/2 lb</span></div>${vs.map(v=>`<div class="ing"><b>${v.emo}</b> <span>8 oz ${v.name} \u00b7 ${v.cut}</span><span class="amt">1/2 lb</span></div>`).join("")}<div class="ing"><b>\uD83C\uDF36</b> <span>${f.spices.join(" \u00b7 ")}</span><span class="amt">bloom</span></div><div class="ing"><b>\uD83E\uDED2</b> <span>${f.fat}</span><span class="amt">fat</span></div><div class="ing"><b>\uD83C\uDF4B</b> <span>${f.finish}</span><span class="amt">finish</span></div></div><div class="section-label">Method</div><div class="steps">${methodSteps().map((s,i)=>`<div class="step"><span class="num">${i+1}</span><span>${s}</span></div>`).join("")}</div><div class="chef-note"><div class="lbl">Chef's note</div><p>${f.note} ${p.sear}</p></div>`;$("gauges").innerHTML=`<div class="gauge"><div class="n">${n.cal}</div><div class="l">calories</div></div><div class="gauge"><div class="n">${n.protein}g</div><div class="l">protein</div></div><div class="gauge"><div class="n">${n.fiber}g</div><div class="l">fiber</div></div><div class="gauge"><div class="n">1 lb</div><div class="l">vegetables</div></div>`;$("extras").innerHTML=`<span>About $${n.cost} / pot</span><span>1 hungry plate / 2 modest plates</span><span>About ${n.time} minutes</span><span>${f.fat}</span>`;$("result").classList.add("show");$("result").scrollIntoView({behavior:"smooth",block:"start"});}
function renderAll(){renderProgress();renderStep();updatePot();renderCombos();}
function applyItem(kind,id,fromDrop){state.combo=null;if(kind==="protein")state.protein=id;if(kind==="veg"){if(!fromDrop&&state.veg.includes(id))state.veg=state.veg.filter(v=>v!==id);else if(state.veg.includes(id)){}else if(state.veg.length<2)state.veg=[...state.veg,id];else state.veg=[state.veg[1],id];}if(kind==="flavor")state.flavor=id;const next=currentStep();state.step=next==="done"?"flavor":next;renderAll();if(isComplete())showResult();else $("result").classList.remove("show");}
document.addEventListener("click",e=>{if(window.__dragMoved)return;const jump=e.target.closest("[data-jump]");if(jump&&!jump.disabled){const to=jump.dataset.jump;if(to==="protein")state.step="protein";if(to==="veg"&&state.protein)state.step="veg";if(to==="flavor"&&state.veg.length===2)state.step="flavor";$("result").classList.remove("show");renderAll();return;}const tile=e.target.closest(".tile");if(tile){applyItem(tile.dataset.kind,tile.dataset.id,false);return;}const combo=e.target.closest(".combo");if(combo)applyCombo(combo.dataset.combo);});
const drag={on:false,moved:false,kind:null,id:null,emo:"\uD83C\uDF72",ghost:null};
function overPot(x,y){const pot=$("potDrop");if(!pot)return false;const r=pot.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;}
function endDrag(x,y){const dropped=drag.moved&&overPot(x,y);const kind=drag.kind,id=drag.id;if(drag.ghost)drag.ghost.remove();document.querySelectorAll(".pot-wrap").forEach(p=>p.classList.remove("hot"));window.__dragMoved=drag.moved;setTimeout(()=>{window.__dragMoved=false;},50);drag.on=false;drag.moved=false;drag.ghost=null;if(dropped)applyItem(kind,id,true);}
document.addEventListener("pointerdown",e=>{const tile=e.target.closest(".tile");if(!tile||e.button)return;drag.on=true;drag.moved=false;drag.kind=tile.dataset.kind;drag.id=tile.dataset.id;drag.emo=tile.dataset.emo||"\uD83C\uDF72";drag.startX=e.clientX;drag.startY=e.clientY;});
document.addEventListener("pointermove",e=>{if(!drag.on)return;const dist=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY);if(!drag.moved&&dist<8)return;if(!drag.moved){drag.moved=true;drag.ghost=document.createElement("div");drag.ghost.className="drag-ghost";drag.ghost.textContent=drag.emo;document.body.appendChild(drag.ghost);}drag.ghost.style.left=e.clientX+"px";drag.ghost.style.top=e.clientY+"px";$("potDrop")&&$("potDrop").classList.toggle("hot",overPot(e.clientX,e.clientY));});
document.addEventListener("pointerup",e=>{if(drag.on)endDrag(e.clientX,e.clientY);});
document.addEventListener("pointercancel",()=>{if(drag.on)endDrag(-1,-1);});
$("startBtn").addEventListener("click",()=>{$("builder").classList.add("show");$("goals").classList.add("show");state.step=currentStep()==="done"?"flavor":currentStep();renderAll();$("builder").scrollIntoView({behavior:"smooth"});});
$("againBtn").addEventListener("click",()=>{state.protein=null;state.veg=[];state.flavor=null;state.combo=null;state.step="protein";$("result").classList.remove("show");renderAll();$("builder").scrollIntoView({behavior:"smooth"});});
$("tweakBtn").addEventListener("click",()=>{state.step="protein";$("result").classList.remove("show");renderAll();$("builder").scrollIntoView({behavior:"smooth"});});
document.querySelectorAll(".goal").forEach(btn=>btn.addEventListener("click",()=>applyGoal(btn.dataset.goal)));
document.addEventListener("click",e=>{if(e.target.id==="surpriseBtn")surprise();if(e.target.id==="nextFlavor"&&state.veg.length===2){state.step="flavor";renderAll();}});
renderAll();
